[package]
name = "dragon-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
dragon-server = { path = ".." }
bytes = "1"
httparse = "1"
tokio = { version = "1", features = ["io-util"] }
toml = "0.8"

[[bin]]
name = "ingress_policy"
path = "fuzz_targets/ingress_policy.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]